
const quotes = [
  "Keep slayin', cuz that glow up ain't gonna reach itself! 💅✨",
  "Stay woke, grind hard, and watch the W come to you! 🚀🔥",
  "Big dreams, bigger hustle. Let's get it! 💯",
  "Good vibes only, no cap! ✌️😎",
  "Work hard, vibe harder. 💼✨",
  "Your energy introduces you before you even speak. Bring that fire! 🔥",
  "Level up daily. No shortcuts, just vibes. 🎮💪",
  "The glow up is a process, not a one-time event. Keep shining! ✨",
  "Keep slayin', cuz that glow up ain't gonna reach itself! 💅✨",
  "Stay woke, grind hard, and watch the W come to you! 🚀🔥",
  "Big dreams, bigger hustle. Let's get it! 💯",
  "Good vibes only, no cap! ✌️😎",
  "Work hard, vibe harder. 💼✨",
  "Your energy introduces you before you even speak. Bring that fire! 🔥",
  "Level up daily. No shortcuts, just vibes. 🎮💪",
  "The glow up is a process, not a one-time event. Keep shining! ✨",
  "Dream big, hustle bigger. The world is yours. 🌍💫",
  "You’re the CEO of your own life — make those boss moves! 👩‍💼👨‍💼",
  "Slay your goals like it’s your cardio. 🏃‍♀️🔥",
  "Don’t let yesterday’s L define today’s W. Keep pushing! 💪",
  "Manifest that magic. Energy flows where attention goes. ✨",
  "Be the vibe you want to attract. Radiate positivity! 🌈",
  "It’s a vibe, not a competition. Support and grow together. 🤝",
  "Own your story. You’re the main character, no cap. 🎬",
  "Haters gonna hate, but your vibe stays undefeated. 💯",
  "Turn your passion into your paycheck. Chase the bag! 💸",
  "If you’re not scared, you’re not growing. Step outta your comfort zone! 🚀",
  "Mood: working hard and making dreams happen. 🔥",
  "Glow up isn’t just looks, it’s mindset. Level up your brain game! 🧠✨",
  "Keep your circle tight and your dreams bigger. 🛡️🌟",
  "You don’t need validation; your vibe is enough. ✌️",
  "Chase progress, not perfection. Every step counts! 🐾",
  "Flex your kindness, it’s the real glow. 💖",
  "Rise like the sun, unstoppable and bright. 🌞",
  "You’re a vibe creator, make the world dance to your tune. 🎶",
  "Wake up. Slay. Repeat. That’s the motto. 🔁",
  "Your vibe attracts your tribe. Build it wisely. 👯‍♂️",
  "Turn setbacks into comebacks, no cap. 💥",
  "Confidence is your best drip. Wear it every day. 💧",
  "Don’t stress, just manifest. The universe has your back. 🌌",
  "Keep the energy high and the drama low. Peace out! ✌️",
  "Your mindset is the filter for your reality. Adjust it daily. 🔄",
  "It’s not luck, it’s hustle + heart. Keep grinding. ❤️",
  "Find your fire and keep it burning bright. 🔥",
  "Boss moves only. Leave the noise behind. 🎯",
  "You’re a vibe, not a label. Break the mold. 🕊️",
  "Celebrate the small wins — they stack up! 🏆",
  "Don’t quit ‘cause it’s hard. Quit ‘cause it’s not you. 🚫",
  "Stay weird, stay wonderful. Your vibe is unique. 🌟",
  "Keep your dreams wild and your hustle wilder. 🌪️",
  "Progress over perfection — every single time. ✅",
  "Good vibes attract good lives. Keep the positive energy flowing. 🌈",
  "You’re the CEO of your vibe. Manage it well. 👩‍💻",
  "Rise, grind, shine — repeat until it’s yours. ✨",
  "Stay humble, hustle hard, be kind. The trifecta of success. 💪",
  "You got the vibe, now bring the tribe. 🤜🤛",
  "Be a voice, not an echo. Make your mark. 🎤",
  "Chase dreams, not clout. The real ones will follow. 🎯",
  "Work until your idols become your rivals. ⚔️",
  "If the plan doesn’t work, change the plan, not the goal. 🔄",
  "Throw kindness around like confetti. 🎉",
  "Be the energy you want to attract — always. ✨",
  "Self-love is the best kind of glow-up. 💖",
  "Keep it 100, always. Authenticity wins. 🏆",
  "Hustle in silence and let your success be the noise. 🔕",
  "Dream so big you scare your fears away. 👻",
  "Vibes speak louder than words. Keep yours positive. 🗣️",
  "Good things take time, so keep grinding. ⏳",
  "Don’t chase people, chase dreams. People will follow. 🏃‍♂️",
  "Your vibe is your currency. Spend it wisely. 💸",
  "Stay fresh, stay focused, stay fearless. 🦁",
  "Embrace the chaos — it’s the spark of creativity. ⚡",
  "Grind now, shine forever. ✨",
  "You are your only limit. Break free! 🚀",
  "Make your haters your motivators. Flip the script. 📖",
  "Turn your vibe up, drown out the noise. 🎧",
  "Your only competition is you yesterday. Beat it. 🏅",
  "Life’s a game — play it with style. 🎮",
  "Manifest that energy you wanna see. 🔮",
  "Build your dreams like a skyscraper — tall and unbreakable. 🏢",
  "Good vibes are contagious. Spread ‘em like wildfire. 🔥",
  "Keep your vibe lit, even on the darkest days. 🕯️",
  "You’re too lit to quit. Keep going! 🔥",
  "Stay golden, stay grinding. 💛",
  "Create, inspire, repeat. Your vibe matters. 🎨",
  "The glow-up starts in your mind. Think big! 💭",
  "If it doesn’t challenge you, it won’t change you. 💪",
  "Be the vibe that turns heads and changes minds. 🧠",
  "Wake up with determination, sleep with satisfaction. 😴",
  "Slay your own dragons, queen/king! 🐉",
  "Your vibe is your signature. Make it unforgettable. ✍️",
  "Progress is a journey, not a sprint. Pace yourself. 🏃",
  "Celebrate the weird, it’s your power. 🌈",
  "Stay rad, stay you. The world needs that energy. 🤘",
  "Your energy is your superpower — use it well. 🦸‍♀️",
  "Keep your head high and your standards higher. 🦅",
  "Dream it. Believe it. Achieve it. Repeat. 🔁",
  "Keep calm and vibe on. ✌️",
  "Your vibe attracts your tribe — build wisely. 👯",
  "Don’t just exist — live, thrive, vibe! 🌟",
  "Self-care isn’t selfish, it’s essential. Recharge your vibe. 🔋",
  "You’re the vibe the world’s been waiting for. 🌍",
  "Good vibes and strong coffee — essentials for success. ☕",
  "Be bold, be brave, be you. No filter needed. 🎭",
  "Your vibe is your story — make it legendary. 📖",
  "Keep the faith, hustle hard, and watch miracles happen. ✨",
  "Make your dreams so big, people get tired just watching. 💤",
  "Life’s short — make your vibe memorable. 🎉",
  "Don’t wait for opportunities — create them. 🔨",
  "Your vibe sets the mood. Set it to greatness. 🎵",
  "Keep your grind tight and your vibe right. 💼",
  "Let your hustle be louder than your doubts. 🔊",
  "Turn your passion into a lifestyle. 🔥",
  "Your vibe is your vibe — own it unapologetically. 💯",
  "Glow up your mind first, then the rest will follow. 💡",
  "Stay hungry for growth, not just success. 🍽️",
  "Vibe high, stress low. Balance is key. ⚖️",
  "Believe in your vibe and the world will too. 🌎",
  "Chase your vibe, not the crowd. Stand out. 🦄",
  "You’re unstoppable when you vibe with purpose. 🎯",
  "Make waves with your energy, not noise. 🌊",
  "Stay loyal to your vibe and your tribe. 🤝",
  "Keep dreaming, keep doing, keep vibing. 🌟",
  "Your vibe is your brand. Make it iconic. 💼",
  "Don’t just talk about it — vibe about it. 🎤",
  "Hustle with heart and vibe with soul. ❤️",
  "Make your vibe contagious — in a good way. 😄",
  "Keep your goals clear and your vibe clearer. 🔍",
  "Own your vibe, own your power. 👑",
  "Your vibe fuels your future. Charge up! ⚡",
  "Celebrate progress, no matter how small. 🎊",
  "Your vibe shapes your reality. Keep it lit! 🔥",
  "Let your vibe be louder than your fears. 🦁",
  "Work hard in silence, let your vibe roar. 🦅",
  "Stay woke, stay hustling. Never settle. 🔥",
  "The best way to predict the future is to vibe for it now. ⏳",
  "Your vibe is your compass — follow it. 🧭",
  "Stay focused, stay fly. 🕶️",
  "Create your vibe like you create your reality. 🎨",
  "Turn your vibe into a movement. 🌍",
  "Be the vibe that brightens someone’s day. ☀️",
  "Your vibe attracts success. Keep it positive. 💯",
  "Stay motivated, stay lit. 🔥",
  "Be the energy that inspires change. ✨",
  "Dreams don’t work unless you vibe with them. 🛠️",
  "You’re a vibe, a whole mood, a lifestyle. Live it. 🧘‍♂️",
  "Good vibes only, period. ✋",
"Keep grinding, keep shining. 🌟",
"Vibe up, stress down. 🧘‍♀️",
"Chase your vibe, not validation. ✔️",
"Your vibe is the blueprint of your life. Build well. 🏗️",
"Stay grounded, stay glowing. 🌱",
"Make your vibe your signature move. 💃",
"Work hard, vibe harder. No days off. 🛠️",
"The glow up starts from within. Light it up! 🔥",
"Don’t just survive, thrive with vibe. 🌿",
"Vibe with intention, hustle with purpose. 🎯",
"Your vibe attracts your destiny. Choose wisely. 🌌",
"Stay true, stay you, stay vibing. 💫",
"Keep your vibe high and your goals higher. 📈",
"Hustle in silence, let your vibe be the noise. 🎧",
"Your vibe is your power. Own it daily. ⚡",
"Stay positive, stay vibin’. ✨",
"Make your vibe a magnet for success. 🧲",
"Work hard, stay humble, vibe loud. 🔊",
"Your vibe is the energy that moves mountains. 🏔️",
"Keep the vibe alive, even on rough days. 🌪️",
"Slay today, vibe forever. 🏆",
"Turn your vibe into your legacy. 🏛️",
"Stay focused, stay fly, stay you. 🦅",
"Create vibes that change lives. 🔥",
"Your vibe is the secret sauce to success. 🍔",
"Be bold, be bright, be vibing. 💡",
"Hustle until your vibe becomes a lifestyle. 🏃‍♂️",
"Your vibe can’t be copied, it’s 100% original. 📝",
"Stay hungry for your dreams, vibe high for your goals. 🍽️",
"Let your vibe speak louder than words. 🎤",
"You’re the vibe that’s changing the game. 🏀",
"Keep vibing, keep thriving. 🌿",
"Your vibe is your vibe — keep it real. ✌️",
"Vibe hard, dream big, stay humble. 💫",
"Good vibes bring good tribes. Build yours. 👯‍♀️",
"Work hard, vibe right, win big. 🏅",
"Your vibe is your story — make it epic. 📖",
"Stay lit, stay grinding, stay winning. 🔥",
"Make your vibe the energy the world needs. 🌍",
"Chase your vibe, not the crowd. Be original. 🦄",
"You’re too lit to quit. Keep shining! ✨",
"Vibe with heart and hustle with soul. ❤️",
"Your vibe is your brand. Build it strong. 💼",
"Keep calm and vibe on. 😎",
"Be the vibe you want to attract. 🌟",
"Manifest the vibe you want. 🔮",
"Good vibes only, always. ✨",
"Turn your vibe into a lifestyle. 🎉",
"Your vibe sets the tone — make it legendary. 🎵",
"Stay true, stay vibing, stay winning. 🏆",
"Your vibe is your power — own it. ⚡",
"Keep your vibe strong and your goals stronger. 💪",
"You got this! Keep vibing! 🙌",
"Slay your vibe, slay your life. 💅",
"Keep the vibe alive. Never settle. 🔥",
"Be the energy that moves mountains. 🏔️",
"Work hard, vibe harder. No days off. 🛠️",
"Your vibe is your vibe. Own it unapologetically. 💯",
"Dream big, hustle harder. Let your vibe show. 🚀",
"Your vibe attracts your tribe — build wisely. 🤝",
"Keep shining, keep vibing. The world needs your light. 🌟",
"Make your vibe contagious — in a good way. 😄",
"Stay fresh, stay focused, stay fearless. 🦁",
"Vibe up, stress down. 🧘‍♂️",
"Keep grinding, keep shining. You’re unstoppable. 💫",
"Your vibe is your story — make it epic. 📖",
"Stay humble, hustle hard, vibe loud. 🔊",
"Make your vibe your signature move. 💃",
"Hustle in silence, let your vibe roar. 🦅",
"Be the vibe that brightens someone’s day. ☀️",
"Your vibe fuels your future. Charge up! ⚡",
"Good vibes are contagious. Spread ‘em like wildfire. 🔥",
"Keep your grind tight and your vibe right. 💼",
"Your energy introduces you before you even speak. Bring that fire! 🔥",
"Stay woke, grind hard, and watch the W come to you! 🚀🔥",
"Big dreams, bigger hustle. Let's get it! 💯",
"Your vibe writes your story — make it a bestseller.",
"Hustle with heart, vibe with soul.",
"Keep your vibe strong and your dreams stronger.",
"Vibe high, aim higher.",
"Work hard in silence, let your vibe do the talking.",
"Your vibe is the spark — light the world.",
"Stay glowing, stay growing.",
"Vibe hard, live loud.",
"Build your vibe like a fortress — unbreakable.",
"Energy flows where your vibe goes.",
"Your vibe sets the rhythm of your life.",
"Own your vibe, own your power.",
"Good vibes, good life, good times.",
"Stay sharp, stay vibing.",
"Vibe on your own terms.",
"Be the energy you want to attract.",
"Your vibe can’t be faked — keep it real.",
"Dream, hustle, vibe, repeat.",
"Keep vibing even when the world doesn’t get it.",
"Vibe positive, attract positive.",
"The grind is real, but so is your vibe.",
"Hustle smart, vibe smarter.",
"Make your vibe a movement.",
"Your vibe is your personal brand — build it big.",
"Vibe strong through every storm.",
"Work hard, vibe right, win big.",
"Stay hungry, stay humble, stay vibing.",
"Let your vibe speak louder than your words.",
"Life’s too short for bad vibes.",
"Vibe well, live well.",
"Your vibe is a reflection of your mindset.",
"Keep the vibe alive and thriving.",
"Your vibe is a magnet — draw greatness in.",
"Shine from within, vibe without limits.",
"Hustle, flow, vibe, grow.",
"Your vibe writes your future’s playlist.",
"Keep your hustle tight and your vibe right.",
"Vibe like you mean it.",
"Be the vibe that others aspire to.",
"Let your vibe be your superpower.",
"Your vibe is your energy currency — spend it wisely.",
"Vibe bold, live bold.",
"Hustle with purpose, vibe with passion.",
"The vibe you give is the vibe you get.",
"Keep your vibe authentic — always.",
"Vibe fresh, vibe fearless.",
"Slay your goals like it’s your cardio 💪🔥.",
"Bad vibes? Nah, I’m too busy winning 👑✨.",
"Glow up? More like glow all day, every day 🌟💅.",
"Make them stop and stare — your vibe is lethal 😎⚡.",
"Hustle like a queen, rest like a boss 👸💼.",
"Own your crown, no permission needed 👑🚫.",
"Too glam to give a damn 💄💋.",
"Boss up, show up, never slow up 🚀💯.",
"Catch flights, not feelings, but still hustle hard ✈️💸.",
"Don’t chase people, chase dreams and the rest will follow 🌈💼.",
"Act like a lady, hustle like a savage 👠🔥.",
"Be a vibe they can’t replicate 🔥💫.",
"Less perfection, more authenticity — bad biitch energy 💁‍♀️✨.",
"Talk less, hustle more, flex hardest 🤫💸.",
"Glow so hard they gotta wear shades 🕶️🌟.",
"Break rules, not hearts, but still own the game 💔👑.",
"Confidence level: Selfie with no filter 🤳🔥.",
"Don’t dim your shine to fit in 🌟🚫.",
"Manifest that bag, then manifest some more 💰🔮.",
"Be savage, not average 🐆🔥.",
"Keep your heels, head, and standards high 👠🧠💯.",
"Your vibe is the ultimate glow-up 🌈💥.",
"Make success your best revenge 💼⚡.",
"Run the world? Baby, I’m already CEO 🌍👸.",
"Stay salty, stay classy, stay unstoppable 🧂💅🚀.",
"Vibe higher than your ex’s standards 🙅‍♀️✨.",
"Fake it till you make it? Nah, just make it 💪🔥.",
"Slay your demons with a smile and a fist 😈✊.",
"Be your own hype squad 🎉🙌.",
"Glow like you own the night — because you do 🌙✨.",
"Keep your circle small and your vibes mighty 👑🔒.",
"Don’t be a snack, be the whole damn meal 🍫🔥.",
"Wake up. Slay. Repeat. 🔁💃.",
"Boss moves only — no time for drama 🕴️🚫.",
"Own your flaws, own your power 💥💪.",
"Be a savage with a soft heart 💖🐅.",
"Talk big, hustle bigger 🗣️💸.",
"Manifest magic and money ✨💵.",
"Don’t compete, create 🔥🎨.",
"Live your truth, no filter needed 📢💯.",
"Slay the day or let the day slay you ☀️👑.",
"Keep your crown straight and your attitude fierce 👸🔥.",
"Stay golden, stay real ✨🌟.",
"Make your haters your motivators 👀💥.",
"Flex like you paid for it — because you did 💳💅.",
"Good vibes only, bad vibes never 💫🚫.",
"Queen energy, 24/7 👑💯.",
"Be unapologetically you — that’s your power 🔥✨.",
"Go where you feel most alive 🌍💃.",
"Make waves, not excuses 🌊💪."
];

async function generateQuoteAndMeme() {
  const loadingElem = document.getElementById('loading');
  const quoteElem = document.getElementById('quote');
  const memeImg = document.getElementById('meme');

  loadingElem.style.display = 'block';
  quoteElem.textContent = '';
  memeImg.src = '';
  memeImg.alt = 'Loading wholesome meme...';

  try {
    if (quotes.length === 0) {
      quoteElem.textContent = "Oops! No quotes found.";
      loadingElem.style.display = 'none';
      return;
    }

    // Pick a random quote from your local quotes array
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    quoteElem.textContent = randomQuote;

    // Fetch wholesome meme
    const memeRes = await fetch('https://meme-api.com/gimme/wholesomememes');
    if (!memeRes.ok) throw new Error('Failed to fetch meme.');
    const memeData = await memeRes.json();
    memeImg.src = memeData.url;
    memeImg.alt = memeData.title;

  } catch (error) {
    console.error(error);
    quoteElem.textContent = 'Oops! Vibes not available RN. Try again later.';
    memeImg.alt = 'No meme available';
  }

  loadingElem.style.display = 'none';
}

function toggleDarkMode() {
  document.body.classList.toggle('dark');
}

function copyQuote() {
  const quote = document.getElementById('quote').textContent;
  if (!quote) {
    alert("Nothing to copy! Generate some vibes first 😎");
    return;
  }
  navigator.clipboard.writeText(quote);
  alert('Quote copied to clipboard 🫶');
}

// On page load, just generate a quote and meme directly from your local quotes array
window.onload = () => {
  generateQuoteAndMeme();
};
